---
title: "ENA Model Zero for Dr. Bowen Hui of UBC"
output:
  html_document:
    df_print: paged
editor_options: 
  chunk_output_type: inline
---
## 0. Setup 
```{r}
library(rENA)
library(magrittr)
library(scales)
library(tidyverse)
setwd("~/Desktop/epistemic_analytics/hui_QE_institute")
df <- read.csv("./datasets/reformatted_hui_data.csv") %>%
  select(-X)
```

## 1. Define units, conversations, codes
```{r}
# units = df[, c("students", "week", "commitment_level")]
units = df[, c("week", "students", "commitment_level")]
conversations = df[, c("students", "week", "commitment_level")]
code_cols = c(
  "Task.done.on.time.1", "Task.done.on.time.2", "Work.accepted.by.others.1", "Work.accepted.by.others.2", "Positive.tone.1",     "Positive.tone.2", "Initiate.conversations.1",  "Initiate.conversations.2",  "Help.others.1", "Help.others.2",                 "Completes.more.tasks.1", "Completes.more.tasks.2", "Assigns.tasks.1", "Assigns.tasks.2", "Review.work.from.others.1",         "Review.work.from.others.2", "Initiate.meeting.1", "Initiate.meeting.2"
)
codes = df[, code_cols]
```

## 2. Accumulate, make set
```{r}
accum = ena.accumulate.data(
  units = units,TIHCI
  conversation = conversations,
  codes = codes,
  window.size.back = 1
)

# set.ena = ena.make.set(enadata = accum)

# set.ena =
#   ena.make.set(
#     enadata = accum,
#     rotation.by = ena.rotate.by.mean,
#     rotation.params = list(
#       accum$meta.data$commitment_level=="low",
#       accum$meta.data$commitment_level=="mid"
#   )
# )

set.ena =
  ena.make.set(
    enadata = accum,
    rotation.by = ena.rotate.by.mean,
    rotation.params = list(
      accum$meta.data$commitment_level=="low",
      accum$meta.data$commitment_level=="high"
  )
)

# set.ena =
#   ena.make.set(
#     enadata = accum,
#     rotation.by = ena.rotate.by.mean,
#     rotation.params = list(
#       accum$meta.data$commitment_level=="mid",
#       accum$meta.data$commitment_level=="high"
#   )
# )
```

## 3. Plot 

### Define points and line weights
```{r}
set <- set.ena
low_points = as.matrix(set$points$commitment_level$low)
mid_points = as.matrix(set$points$commitment_level$mid)
high_points = as.matrix(set$points$commitment_level$high)
points_max = max(low_points, mid_points, high_points)

# low_points_scaled = scales::rescale(low_points,
#                                     c(0,max(as.matrix(set$rotation$nodes))), c(0,points_max))
# mid_points_scaled = scales::rescale(mid_points,
#                                      c(0,max(as.matrix(set$rotation$nodes))), c(0,points_max))
# high_points_scaled = scales::rescale(high_points,
#                                      c(0,max(as.matrix(set$rotation$nodes))), c(0,points_max))

low_lw = as.matrix(set$line.weights$commitment_level$low)
low_mean = as.vector(colMeans(low_lw))
mid_lw = as.matrix(set$line.weights$commitment_level$mid)
mid_mean = as.vector(colMeans(mid_lw))
high_lw = as.matrix(set$line.weights$commitment_level$high)
high_mean = as.vector(colMeans(high_lw))
```

### Plot for low students
```{r}
plot_low = ena.plot(set, title = "Mean Low Network", font.family = "Times") %>%
  #ena.plot.points(points = low_points, colors = c("red")) %>%
  ena.plot.group(points = low_points, colors =c("red"),
                         confidence.interval = "box") %>% 
  ena.plot.network(network = low_mean, colors = c("red"), labels = FALSE)
plot_low$plot 
```

### Plot for mid students
```{r}
plot_mid = ena.plot(set, title = "Mean Mid Network") %>%
  #ena.plot.points(points = mid_points, colors = c("blue")) %>%
    ena.plot.group(points = mid_points, colors= c("blue"),
                         confidence.interval = "box") %>% 
  ena.plot.network(network = mid_mean, colors = c("blue"), labels = FALSE)
plot_mid$plot
```

### Plot for high students
```{r}
plot_high = ena.plot(set, title = "Mean High Network") %>%
 #  ena.plot.points(points = high_points, colors = c("orange")) %>%
  ena.plot.group(points = high_points, colors =c("purple"),
                         confidence.interval = "box") %>% 
  ena.plot.network(network = high_mean, colors = c("purple"), labels = FALSE)
plot_high$plot
```

## Difference plots 
```{r}
# Low vs Mid
subtracted_low_mid = low_mean - mid_mean
low_v_mid <- ena.plot(set, title = "Low v. Mid", font.family = "Times") %>% 
          ena.plot.group(point = low_points, colors =c("red"),
                         confidence.interval = "box") %>% 
          ena.plot.group(point = mid_points, colors =c("blue"), 
                         confidence.interval = "box") %>%
          ena.plot.network(network = subtracted_low_mid * 6, colors = c("red", "blue"), labels = FALSE)

low_v_mid$plot
```


```{r}
# Low vs. High 
subtracted_low_high = low_mean - high_mean
low_v_high <- ena.plot(set, title = "Low v. High", font.family = "Times") %>% 
          ena.plot.group(point = low_points, colors =c("red"),
                         confidence.interval = "box") %>% 
          ena.plot.group(point = high_points, colors =c("purple"), 
                         confidence.interval = "box") %>%
          ena.plot.network(network = subtracted_low_high * 6, colors = c("red", "purple"), labels = FALSE)

low_v_high$plot

```

```{r}
# Mid vs. High
subtracted_mid_high = mid_mean - high_mean
mid_v_high <- ena.plot(set, title = "Mid v. High", font.family = "Times") %>% 
          ena.plot.group(point = mid_points, colors =c("blue"),
                         confidence.interval = "box") %>% 
          ena.plot.group(point = high_points, colors =c("purple"), 
                         confidence.interval = "box") %>%
          ena.plot.network(network = subtracted_mid_high * 6, colors = c("blue", "purple"), labels = FALSE)

mid_v_high$plot
```

## ENA Score Plot 

```{r}
ena_scores <- ena.plot(set, title = "ENA Scores", font.family = "Times") %>%
  ena.plot.group(point = low_points, colors =c("red"),
                         confidence.interval = "box") %>% 
  ena.plot.group(point = mid_points, colors =c("blue"),
                         confidence.interval = "box") %>%
  ena.plot.group(point = high_points, colors =c("purple"), 
                         confidence.interval = "box") 
ena_scores$plot
```


## Statistics 
```{r}
library(effsize)
# Can't verify that ENA scores are normally distributed, sample size too big for Shapiro-Wilk test to verify normality. Assumption of independence satisfied, proceed with Mann-Whitney U-Test instead. 

low <- set$points$commitment_level$low$SVD2
mid <- set$points$commitment_level$mid$SVD2
high <- set$points$commitment_level$high$SVD2

# low <- set$points$commitment_level$low$MR1
# mid <- set$points$commitment_level$mid$MR1
# high <- set$points$commitment_level$high$MR1

# Low v. Mid

# Mann-Whitney
wilcox.test(low, mid)

# Cohen's d 
cohen.d(low, mid)

# Low v. High

# Mann-Whitney
wilcox.test(low, high)

# Cohen's d 
cohen.d(low, high)

# Mid v. High

# Mann-Whitney
wilcox.test(mid, high)

# Cohen's d 
cohen.d(mid, high)


```

```{r}
# Base rate discovery 
low <- df %>% 
  filter(commitment_level == "low") %>%
  select(-c("students", "week", "commitment_level")) 
low <- as.data.frame(colSums(low)) %>%
  rename(low = `colSums(low)`)

low$low <- low$low / 19500

mid <- df %>% 
  filter(commitment_level == "mid") %>% 
  select(-c("students", "week", "commitment_level"))
mid <- as.data.frame(colSums(mid)) %>%
  rename(mid = `colSums(mid)`)

mid$mid <- mid$mid / 19500

high <- df %>%
  filter(commitment_level == "high") %>% 
  select(-c("students", "week", "commitment_level"))
high <- as.data.frame(colSums(high)) %>%
  rename(high = `colSums(high)`)

high$high <- high$high / 19500

binded <- cbind(low, mid, high)


  


```


